import type { UsDiscoveryCandidate } from '@office-unify/shared-types';

type UsDiscoverySeed = UsDiscoveryCandidate & {
  keywords: string[];
};

export type BuildUsDiscoveryCandidatesInput = {
  preferredThemes?: string[];
  excludeSymbols?: string[];
  limit?: number;
};

export const US_DISCOVERY_SEEDS: readonly UsDiscoverySeed[] = [
  {
    symbol: 'VRT',
    name: 'Vertiv',
    market: 'US',
    exchange: 'NYSE',
    theme: 'AI data center power and cooling',
    reasonKo: 'AI 데이터센터 전력·냉각 인프라와 연결되는 관찰 후보입니다.',
    evidenceKo: ['데이터센터 전력 밀도 상승 테마', '냉각·전원 장비 수요 관찰'],
    riskKo: ['시세 미확인 상태에서는 가격 판단에 사용하지 마세요.', '설비 투자 사이클 둔화 시 변동성이 커질 수 있습니다.'],
    confidence: 'medium',
    discoverySource: 'theme_seed',
    isWatchlist: false,
    isTradeCandidate: false,
    actionHintKo: '시세 미확인 상태입니다. 가격 판단 전에 quote/provider 상태를 확인하세요.',
    keywords: ['ai', 'data center', 'datacenter', 'power', 'cooling', 'infrastructure', '전력', '냉각', '데이터센터'],
  },
  {
    symbol: 'NVDA',
    name: 'NVIDIA',
    market: 'US',
    exchange: 'NASDAQ',
    theme: 'AI accelerator',
    reasonKo: 'AI 가속기와 데이터센터 투자 흐름을 대표하는 관찰 후보입니다.',
    evidenceKo: ['AI 서버 수요의 핵심 공급망', '클라우드·모델 학습 투자와 연결'],
    riskKo: ['시세 미확인 상태에서는 가격 판단에 사용하지 마세요.', '높은 기대치가 밸류에이션 변동으로 이어질 수 있습니다.'],
    confidence: 'medium',
    discoverySource: 'theme_seed',
    isWatchlist: false,
    isTradeCandidate: false,
    actionHintKo: '시세 미확인 상태입니다. 가격 판단 전에 quote/provider 상태를 확인하세요.',
    keywords: ['ai', 'gpu', 'accelerator', 'data center', 'semiconductor', '반도체', '가속기'],
  },
  {
    symbol: 'AVGO',
    name: 'Broadcom',
    market: 'US',
    exchange: 'NASDAQ',
    theme: 'AI networking semiconductor',
    reasonKo: 'AI 네트워킹과 맞춤형 반도체 수요를 관찰할 수 있는 후보입니다.',
    evidenceKo: ['데이터센터 네트워크 투자와 연결', 'AI ASIC 테마 관찰'],
    riskKo: ['시세 미확인 상태에서는 가격 판단에 사용하지 마세요.', '대형 고객 투자 속도에 민감할 수 있습니다.'],
    confidence: 'medium',
    discoverySource: 'theme_seed',
    isWatchlist: false,
    isTradeCandidate: false,
    actionHintKo: '시세 미확인 상태입니다. 가격 판단 전에 quote/provider 상태를 확인하세요.',
    keywords: ['ai', 'networking', 'asic', 'semiconductor', 'data center', '반도체'],
  },
  {
    symbol: 'ETN',
    name: 'Eaton',
    market: 'US',
    exchange: 'NYSE',
    theme: 'power grid equipment',
    reasonKo: '전력망 증설과 전기화 투자 흐름을 관찰할 수 있는 후보입니다.',
    evidenceKo: ['전력 인프라 확충 테마', '데이터센터 전력 수요와 연결'],
    riskKo: ['시세 미확인 상태에서는 가격 판단에 사용하지 마세요.', '산업 설비 투자 둔화에 영향을 받을 수 있습니다.'],
    confidence: 'medium',
    discoverySource: 'theme_seed',
    isWatchlist: false,
    isTradeCandidate: false,
    actionHintKo: '시세 미확인 상태입니다. 가격 판단 전에 quote/provider 상태를 확인하세요.',
    keywords: ['power', 'grid', 'electrification', 'data center', '전력', '전력망'],
  },
  {
    symbol: 'GEV',
    name: 'GE Vernova',
    market: 'US',
    exchange: 'NYSE',
    theme: 'power generation and grid',
    reasonKo: '발전·전력망 투자와 연결되는 미국 인프라 관찰 후보입니다.',
    evidenceKo: ['전력 수요 증가 테마', '그리드 장비와 발전 포트폴리오'],
    riskKo: ['시세 미확인 상태에서는 가격 판단에 사용하지 마세요.', '정책·수주 사이클에 따라 변동성이 커질 수 있습니다.'],
    confidence: 'low',
    discoverySource: 'theme_seed',
    isWatchlist: false,
    isTradeCandidate: false,
    actionHintKo: '시세 미확인 상태입니다. 가격 판단 전에 quote/provider 상태를 확인하세요.',
    keywords: ['power', 'grid', 'generation', 'energy', '전력', '발전'],
  },
  {
    symbol: 'ISRG',
    name: 'Intuitive Surgical',
    market: 'US',
    exchange: 'NASDAQ',
    theme: 'robotics automation',
    reasonKo: '로보틱스와 자동화 테마를 의료 장비 관점에서 관찰할 수 있는 후보입니다.',
    evidenceKo: ['수술 로봇 설치 기반', '자동화 장비 채택 흐름'],
    riskKo: ['시세 미확인 상태에서는 가격 판단에 사용하지 마세요.', '의료 장비 지출과 규제 환경을 함께 확인해야 합니다.'],
    confidence: 'low',
    discoverySource: 'theme_seed',
    isWatchlist: false,
    isTradeCandidate: false,
    actionHintKo: '시세 미확인 상태입니다. 가격 판단 전에 quote/provider 상태를 확인하세요.',
    keywords: ['robotics', 'automation', 'medical', '로봇', '자동화'],
  },
  {
    symbol: 'AMAT',
    name: 'Applied Materials',
    market: 'US',
    exchange: 'NASDAQ',
    theme: 'semiconductor equipment',
    reasonKo: '반도체 장비 투자 사이클을 관찰하는 미국 후보입니다.',
    evidenceKo: ['웨이퍼 장비 공급망', 'AI 반도체 증설 테마와 연결'],
    riskKo: ['시세 미확인 상태에서는 가격 판단에 사용하지 마세요.', '반도체 설비투자 사이클 둔화 위험이 있습니다.'],
    confidence: 'low',
    discoverySource: 'theme_seed',
    isWatchlist: false,
    isTradeCandidate: false,
    actionHintKo: '시세 미확인 상태입니다. 가격 판단 전에 quote/provider 상태를 확인하세요.',
    keywords: ['semiconductor', 'equipment', 'ai', '반도체', '장비'],
  },
  {
    symbol: 'MSFT',
    name: 'Microsoft',
    market: 'US',
    exchange: 'NASDAQ',
    theme: 'AI software infrastructure',
    reasonKo: 'AI 소프트웨어와 클라우드 인프라 흐름을 함께 관찰할 수 있는 후보입니다.',
    evidenceKo: ['클라우드 인프라 투자', 'AI 서비스와 생산성 소프트웨어 연결'],
    riskKo: ['시세 미확인 상태에서는 가격 판단에 사용하지 마세요.', '대형주 기대치와 클라우드 성장률을 확인해야 합니다.'],
    confidence: 'medium',
    discoverySource: 'theme_seed',
    isWatchlist: false,
    isTradeCandidate: false,
    actionHintKo: '시세 미확인 상태입니다. 가격 판단 전에 quote/provider 상태를 확인하세요.',
    keywords: ['ai', 'software', 'cloud', 'infrastructure', '소프트웨어', '클라우드'],
  },
  {
    symbol: 'AMD',
    name: 'Advanced Micro Devices',
    market: 'US',
    exchange: 'NASDAQ',
    theme: 'AI accelerator and CPU',
    reasonKo: 'AI 가속기와 서버 CPU 공급망을 함께 관찰할 수 있는 후보입니다.',
    evidenceKo: ['AI 서버 반도체 수요', '데이터센터 CPU/GPU 경쟁 구도'],
    riskKo: ['시세 미확인 상태에서는 가격 판단에 사용하지 마세요.', '제품 전환과 경쟁 강도에 민감할 수 있습니다.'],
    confidence: 'low',
    discoverySource: 'theme_seed',
    isWatchlist: false,
    isTradeCandidate: false,
    actionHintKo: '시세 미확인 상태입니다. 가격 판단 전에 quote/provider 상태를 확인하세요.',
    keywords: ['ai', 'gpu', 'cpu', 'semiconductor', 'data center', '반도체'],
  },
  {
    symbol: 'SMCI',
    name: 'Super Micro Computer',
    market: 'US',
    exchange: 'NASDAQ',
    theme: 'AI server systems',
    reasonKo: 'AI 서버 시스템과 랙 단위 데이터센터 투자 흐름을 관찰하는 후보입니다.',
    evidenceKo: ['AI 서버 공급망', '고밀도 서버 구축 테마'],
    riskKo: ['시세 미확인 상태에서는 가격 판단에 사용하지 마세요.', '재무·공급망 이슈 확인이 필요합니다.'],
    confidence: 'low',
    discoverySource: 'theme_seed',
    isWatchlist: false,
    isTradeCandidate: false,
    actionHintKo: '시세 미확인 상태입니다. 가격 판단 전에 quote/provider 상태를 확인하세요.',
    keywords: ['ai', 'server', 'data center', 'hardware', '데이터센터'],
  },
  {
    symbol: 'DELL',
    name: 'Dell Technologies',
    market: 'US',
    exchange: 'NYSE',
    theme: 'AI server infrastructure',
    reasonKo: 'AI 서버와 기업 인프라 투자 흐름을 관찰할 수 있는 후보입니다.',
    evidenceKo: ['서버 인프라 수요', '기업 IT 투자와 연결'],
    riskKo: ['시세 미확인 상태에서는 가격 판단에 사용하지 마세요.', '서버 마진과 수요 변동을 확인해야 합니다.'],
    confidence: 'low',
    discoverySource: 'theme_seed',
    isWatchlist: false,
    isTradeCandidate: false,
    actionHintKo: '시세 미확인 상태입니다. 가격 판단 전에 quote/provider 상태를 확인하세요.',
    keywords: ['ai', 'server', 'data center', 'infrastructure', 'hardware'],
  },
  {
    symbol: 'PWR',
    name: 'Quanta Services',
    market: 'US',
    exchange: 'NYSE',
    theme: 'power grid construction',
    reasonKo: '전력망 시공과 유틸리티 인프라 투자 흐름을 관찰할 수 있는 후보입니다.',
    evidenceKo: ['송배전 투자', '전력망 확충 테마'],
    riskKo: ['시세 미확인 상태에서는 가격 판단에 사용하지 마세요.', '프로젝트 수주와 비용 변동에 민감합니다.'],
    confidence: 'low',
    discoverySource: 'theme_seed',
    isWatchlist: false,
    isTradeCandidate: false,
    actionHintKo: '시세 미확인 상태입니다. 가격 판단 전에 quote/provider 상태를 확인하세요.',
    keywords: ['power', 'grid', 'utility', 'construction', '전력망'],
  },
  {
    symbol: 'CAT',
    name: 'Caterpillar',
    market: 'US',
    exchange: 'NYSE',
    theme: 'industrial power and infrastructure',
    reasonKo: '전력·인프라 투자와 산업 장비 수요를 관찰하는 후보입니다.',
    evidenceKo: ['인프라 설비 수요', '발전·건설 장비와 연결'],
    riskKo: ['시세 미확인 상태에서는 가격 판단에 사용하지 마세요.', '경기와 원자재 투자 사이클 영향을 받습니다.'],
    confidence: 'low',
    discoverySource: 'theme_seed',
    isWatchlist: false,
    isTradeCandidate: false,
    actionHintKo: '시세 미확인 상태입니다. 가격 판단 전에 quote/provider 상태를 확인하세요.',
    keywords: ['power', 'grid', 'industrial', 'infrastructure', '장비'],
  },
  {
    symbol: 'TER',
    name: 'Teradyne',
    market: 'US',
    exchange: 'NASDAQ',
    theme: 'robotics and semiconductor test',
    reasonKo: '로보틱스와 반도체 테스트 장비를 함께 관찰할 수 있는 후보입니다.',
    evidenceKo: ['협동로봇·자동화 테마', '반도체 테스트 장비 수요'],
    riskKo: ['시세 미확인 상태에서는 가격 판단에 사용하지 마세요.', '반도체 장비 사이클에 민감합니다.'],
    confidence: 'low',
    discoverySource: 'theme_seed',
    isWatchlist: false,
    isTradeCandidate: false,
    actionHintKo: '시세 미확인 상태입니다. 가격 판단 전에 quote/provider 상태를 확인하세요.',
    keywords: ['robotics', 'automation', 'semiconductor', 'test', '로봇', '자동화'],
  },
  {
    symbol: 'SYM',
    name: 'Symbotic',
    market: 'US',
    exchange: 'NASDAQ',
    theme: 'warehouse automation robotics',
    reasonKo: '물류 자동화와 창고 로봇 테마를 관찰할 수 있는 후보입니다.',
    evidenceKo: ['물류 자동화 수요', '로봇 기반 창고 운영'],
    riskKo: ['시세 미확인 상태에서는 가격 판단에 사용하지 마세요.', '고객 집중도와 프로젝트 속도를 확인해야 합니다.'],
    confidence: 'low',
    discoverySource: 'theme_seed',
    isWatchlist: false,
    isTradeCandidate: false,
    actionHintKo: '시세 미확인 상태입니다. 가격 판단 전에 quote/provider 상태를 확인하세요.',
    keywords: ['robotics', 'automation', 'warehouse', 'logistics', '로봇'],
  },
  {
    symbol: 'PATH',
    name: 'UiPath',
    market: 'US',
    exchange: 'NYSE',
    theme: 'software automation',
    reasonKo: '업무 자동화 소프트웨어와 AI 에이전트 전환 흐름을 관찰하는 후보입니다.',
    evidenceKo: ['자동화 소프트웨어 수요', 'AI 업무 흐름 연결'],
    riskKo: ['시세 미확인 상태에서는 가격 판단에 사용하지 마세요.', '성장률 둔화와 경쟁을 확인해야 합니다.'],
    confidence: 'low',
    discoverySource: 'theme_seed',
    isWatchlist: false,
    isTradeCandidate: false,
    actionHintKo: '시세 미확인 상태입니다. 가격 판단 전에 quote/provider 상태를 확인하세요.',
    keywords: ['automation', 'software', 'ai', 'workflow', '자동화'],
  },
  {
    symbol: 'ROBO',
    name: 'ROBO Global Robotics and Automation ETF',
    market: 'US',
    exchange: 'NYSEARCA',
    theme: 'robotics automation ETF',
    reasonKo: '로보틱스·자동화 테마를 ETF 관점에서 넓게 관찰하는 후보입니다.',
    evidenceKo: ['로보틱스 테마 분산 노출', '자동화 공급망 관찰'],
    riskKo: ['시세 미확인 상태에서는 가격 판단에 사용하지 마세요.', 'ETF 구성 종목과 유동성을 확인해야 합니다.'],
    confidence: 'low',
    discoverySource: 'theme_seed',
    isWatchlist: false,
    isTradeCandidate: false,
    actionHintKo: '시세 미확인 상태입니다. 가격 판단 전에 quote/provider 상태를 확인하세요.',
    keywords: ['robotics', 'automation', 'etf', '로봇', '자동화'],
  },
  {
    symbol: 'ASML',
    name: 'ASML Holding',
    market: 'US',
    exchange: 'NASDAQ',
    theme: 'semiconductor lithography equipment',
    reasonKo: '첨단 반도체 노광 장비 공급망을 관찰할 수 있는 후보입니다.',
    evidenceKo: ['EUV 노광 장비', '첨단 공정 투자와 연결'],
    riskKo: ['시세 미확인 상태에서는 가격 판단에 사용하지 마세요.', '수출 규제와 설비투자 사이클을 확인해야 합니다.'],
    confidence: 'low',
    discoverySource: 'theme_seed',
    isWatchlist: false,
    isTradeCandidate: false,
    actionHintKo: '시세 미확인 상태입니다. 가격 판단 전에 quote/provider 상태를 확인하세요.',
    keywords: ['semiconductor', 'equipment', 'lithography', '반도체', '장비'],
  },
  {
    symbol: 'LRCX',
    name: 'Lam Research',
    market: 'US',
    exchange: 'NASDAQ',
    theme: 'semiconductor wafer equipment',
    reasonKo: '식각·증착 장비와 반도체 설비투자 사이클을 관찰하는 후보입니다.',
    evidenceKo: ['웨이퍼 장비 공급망', '메모리·파운드리 투자와 연결'],
    riskKo: ['시세 미확인 상태에서는 가격 판단에 사용하지 마세요.', '메모리 투자 사이클에 민감합니다.'],
    confidence: 'low',
    discoverySource: 'theme_seed',
    isWatchlist: false,
    isTradeCandidate: false,
    actionHintKo: '시세 미확인 상태입니다. 가격 판단 전에 quote/provider 상태를 확인하세요.',
    keywords: ['semiconductor', 'equipment', 'wafer', '반도체', '장비'],
  },
  {
    symbol: 'KLAC',
    name: 'KLA',
    market: 'US',
    exchange: 'NASDAQ',
    theme: 'semiconductor process control',
    reasonKo: '반도체 공정 제어와 검사 장비 수요를 관찰하는 후보입니다.',
    evidenceKo: ['공정 검사 장비', '첨단 공정 수율 관리'],
    riskKo: ['시세 미확인 상태에서는 가격 판단에 사용하지 마세요.', '설비투자 둔화 영향을 받을 수 있습니다.'],
    confidence: 'low',
    discoverySource: 'theme_seed',
    isWatchlist: false,
    isTradeCandidate: false,
    actionHintKo: '시세 미확인 상태입니다. 가격 판단 전에 quote/provider 상태를 확인하세요.',
    keywords: ['semiconductor', 'equipment', 'inspection', 'process', '반도체'],
  },
  {
    symbol: 'ON',
    name: 'ON Semiconductor',
    market: 'US',
    exchange: 'NASDAQ',
    theme: 'power semiconductor',
    reasonKo: '전력 반도체와 자동차·산업 전장 수요를 관찰하는 후보입니다.',
    evidenceKo: ['전력 반도체 수요', '전기차·산업 장비와 연결'],
    riskKo: ['시세 미확인 상태에서는 가격 판단에 사용하지 마세요.', '자동차·산업 수요 둔화를 확인해야 합니다.'],
    confidence: 'low',
    discoverySource: 'theme_seed',
    isWatchlist: false,
    isTradeCandidate: false,
    actionHintKo: '시세 미확인 상태입니다. 가격 판단 전에 quote/provider 상태를 확인하세요.',
    keywords: ['semiconductor', 'power', 'automotive', 'industrial', '전력반도체'],
  },
  {
    symbol: 'NOW',
    name: 'ServiceNow',
    market: 'US',
    exchange: 'NYSE',
    theme: 'AI workflow software',
    reasonKo: 'AI 업무 자동화와 엔터프라이즈 워크플로 소프트웨어를 관찰하는 후보입니다.',
    evidenceKo: ['기업 워크플로 자동화', 'AI 서비스 통합'],
    riskKo: ['시세 미확인 상태에서는 가격 판단에 사용하지 마세요.', '기업 소프트웨어 지출 둔화를 확인해야 합니다.'],
    confidence: 'low',
    discoverySource: 'theme_seed',
    isWatchlist: false,
    isTradeCandidate: false,
    actionHintKo: '시세 미확인 상태입니다. 가격 판단 전에 quote/provider 상태를 확인하세요.',
    keywords: ['software', 'ai', 'workflow', 'cloud', '소프트웨어'],
  },
  {
    symbol: 'PLTR',
    name: 'Palantir Technologies',
    market: 'US',
    exchange: 'NASDAQ',
    theme: 'AI data platform',
    reasonKo: 'AI 데이터 플랫폼과 공공·기업 분석 수요를 관찰하는 후보입니다.',
    evidenceKo: ['AI 데이터 분석 플랫폼', '공공·기업 고객 확장'],
    riskKo: ['시세 미확인 상태에서는 가격 판단에 사용하지 마세요.', '높은 기대치와 계약 변동성을 확인해야 합니다.'],
    confidence: 'low',
    discoverySource: 'theme_seed',
    isWatchlist: false,
    isTradeCandidate: false,
    actionHintKo: '시세 미확인 상태입니다. 가격 판단 전에 quote/provider 상태를 확인하세요.',
    keywords: ['software', 'ai', 'data', 'platform', '소프트웨어'],
  },
  {
    symbol: 'SNOW',
    name: 'Snowflake',
    market: 'US',
    exchange: 'NYSE',
    theme: 'cloud data platform',
    reasonKo: '클라우드 데이터 플랫폼과 AI 데이터 인프라 수요를 관찰하는 후보입니다.',
    evidenceKo: ['데이터 클라우드 수요', 'AI 데이터 준비 흐름'],
    riskKo: ['시세 미확인 상태에서는 가격 판단에 사용하지 마세요.', '사용량 기반 성장률 변동을 확인해야 합니다.'],
    confidence: 'low',
    discoverySource: 'theme_seed',
    isWatchlist: false,
    isTradeCandidate: false,
    actionHintKo: '시세 미확인 상태입니다. 가격 판단 전에 quote/provider 상태를 확인하세요.',
    keywords: ['software', 'cloud', 'data', 'ai', '데이터'],
  },
  {
    symbol: 'CRWD',
    name: 'CrowdStrike',
    market: 'US',
    exchange: 'NASDAQ',
    theme: 'AI cybersecurity software',
    reasonKo: 'AI 보안 운영과 클라우드 보안 소프트웨어를 관찰하는 후보입니다.',
    evidenceKo: ['엔드포인트 보안 수요', 'AI 기반 보안 운영'],
    riskKo: ['시세 미확인 상태에서는 가격 판단에 사용하지 마세요.', '보안 사고와 고객 지출 변동을 확인해야 합니다.'],
    confidence: 'low',
    discoverySource: 'theme_seed',
    isWatchlist: false,
    isTradeCandidate: false,
    actionHintKo: '시세 미확인 상태입니다. 가격 판단 전에 quote/provider 상태를 확인하세요.',
    keywords: ['software', 'cybersecurity', 'ai', 'cloud', '보안'],
  },
];

function normalizeTheme(value: string): string {
  return value.trim().toLowerCase();
}

function seedScore(seed: UsDiscoverySeed, preferredThemes: string[]): number {
  if (preferredThemes.length === 0) return 0;
  const haystack = normalizeTheme([seed.symbol, seed.name, seed.theme, seed.reasonKo, ...seed.keywords].join(' '));
  return preferredThemes.reduce((score, theme) => {
    const normalized = normalizeTheme(theme);
    if (!normalized) return score;
    if (haystack.includes(normalized)) return score + 3;
    return score + seed.keywords.filter((keyword) => normalized.includes(normalizeTheme(keyword))).length;
  }, 0);
}

export function buildUsDiscoveryCandidates(input: BuildUsDiscoveryCandidatesInput = {}): UsDiscoveryCandidate[] {
  const limit = Math.max(0, Math.min(input.limit ?? 1, 3));
  if (limit === 0) return [];

  const excluded = new Set((input.excludeSymbols ?? []).map((symbol) => normalizeTheme(symbol.replace(/^US:/i, ''))));
  const preferredThemes = (input.preferredThemes ?? []).filter((theme) => theme.trim().length > 0);

  return US_DISCOVERY_SEEDS.filter((seed) => !excluded.has(normalizeTheme(seed.symbol)))
    .map((seed, index) => ({ seed, index, score: seedScore(seed, preferredThemes) }))
    .sort((a, b) => b.score - a.score || a.index - b.index)
    .slice(0, limit)
    .map(({ seed }) => ({
      symbol: seed.symbol,
      name: seed.name,
      market: seed.market,
      exchange: seed.exchange,
      theme: seed.theme,
      reasonKo: seed.reasonKo,
      evidenceKo: seed.evidenceKo,
      riskKo: seed.riskKo,
      confidence: seed.confidence,
      discoverySource: seed.discoverySource,
      isWatchlist: seed.isWatchlist,
      isTradeCandidate: seed.isTradeCandidate,
      actionHintKo: seed.actionHintKo,
    }));
}
